version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Sean12697
  assignees:
  - Sean12697
  ignore:
  - dependency-name: "@tensorflow/tfjs-node"
    versions:
    - 2.8.6
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
    - 3.5.0
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
    - 0.28.0
  - dependency-name: bl
    versions:
    - 4.0.4
